### ISSUE TITLE
Unable add Images

### ISSUE THREAD

**Issue by PuranBareth** [battleplayer02/sql#8]
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="CSS\login.css">
    </head>
    <body>
       <div class = "main">
           <div class="frm-box">
             <div class= "button-box">
                 <div class="btn"> </div>
                 <button type= "button" class = " btn-toggle">LogIn</button> 
                 <button type= "button" class = " btn-toggle">Register</button> 

             </div>
             <div class="social-icons"> 
                 <img src="Images\fb.png">
                 <img src="">
                 <img src="">
             </div>
        
        </div>
       </div>
        
        <script src="" async defer></script>
    </body>
</html>

**Comment by battleplayer02** [comment]
your scr attribute's value might not be right check whether there is an image existing inside Images fb.png
